- name: Create Jenkins Slave Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: myResourceGroup
      location: eastus
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: myResourceGroup
      name: Jenkins-MasterVNET
      address_prefixes: "10.0.0.0/16"
#  - name: Add subnet
#    azure_rm_subnet:
#      resource_group: myResourceGroup
#      name: mySubnet
#      address_prefix: "10.0.1.0/24"
#      virtual_network: myVnet
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: myResourceGroup
      allocation_method: Static
      name: Jenkins-SlavePublicIP
    register: output_ip_address
  - name: Dump public IP for VM which will be created
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}."
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: myResourceGroup
      name: Jenkins-SlaveNSG
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: myResourceGroup
      name: Jenkins-SlaveVMNic
      virtual_network: Jenkins-MasterVNET
      subnet: Jenkins-MasterSubnet
      public_ip_name: Jenkins-SlavePublicIP
      security_group: Jenkins-SlaveNSG
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: myResourceGroup
      name: Jenkins-Slave
      vm_size: Standard_DS1_v2
      admin_username: azureuser
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDNvKC/XXvKGITkFb3BC4S8qINKP6GXgbr0IiiPXpTZmdDTck6ybSYyCyZXAaZeSUl/lwIOzvQb8XwY/aaote263raYg4fyroLbcdkrPVsy7CyYPo5/4q3PXR7PeWZV8cLAzQgTF/barqDh8lioZwVo3SqRIkgz2SKwJAlQEfqGVYz5n+2o8mUGxxsdML0g8rEfyhWWtEGoZ+qgEXFM7Q6Bdovz2QO4oO7L1jq58znYYg3pbyvmTWCZJL3GUeip5KSh/cGb3lPzQMGn47sA8daykhjVsOalKCo2pt31Z6abj55LTNkpFHX1DnGQ+QlotFhjERR78+4WbHe3ZgkPOYPb
      network_interfaces: Jenkins-SlaveVMNic
      image:
        offer: UbuntuServer
        publisher: Canonical
        sku: '18.04-LTS'
        version: latest
